version: '3.8'
services:
  "web-app":
    build: "./web-app"
    ports:
      - "8080:8080"
    volumes:
      - "./web-app/src:/web-app/src"
      
  "database":
    build: "./database"
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_DATABASE: "hots_builds_database"
    ports:
      - "3306:3306"

  session-redis:
    build: "./session-redis"
    ports:
      - "6379:6379"

  "postgresql":
    build: "./postgreSQL"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=abc123
    ports:
      - '5432:5432'

  spa:
    image: nginx
    ports:
      - "49152:49152"
    volumes:
      - ./spa/nginx.conf:/etc/nginx/nginx.conf
      - ./spa/index.html:/data/www/index.html
      - ./spa/static/js/navigation.js:/data/www/navigation.js
      - ./spa/static/css/styles.css:/data/www/styles.css
