version: '3.8'
services:
  "web-app":
    build: "./web-app"
    ports:
      - "8080:8080"
    volumes:
      - "./web-app/src:/web-app/src"
  "database":
    build: "./database"
    environment:
      MYSQL_ROOT_PASSWORD: "abc123"
      MYSQL_DATABASE: "my-platform"
    ports:
      - "3306:3306"
